export type RunDataAliasGroup = {
  key: string
  aliases: string[]
}

export const TRACK_RUN_OUTPUT_ALIAS_GROUPS: readonly RunDataAliasGroup[] = [
  { key: 'tier', aliases: ['Tier'] },
  { key: 'wave', aliases: ['Wave'] },
  { key: 'roundDuration', aliases: ['Real Time', 'duration'] },
  { key: 'totalCoins', aliases: ['Coins earned', 'Coins Earned', 'coins'] },
  { key: 'totalCells', aliases: ['Cells Earned', 'cells'] },
  { key: 'totalDice', aliases: ['Reroll Shards Earned', 'dice', 'rerollShards'] },
  { key: 'killedBy', aliases: ['Killed By'] },
  { key: 'cashEarned', aliases: ['Cash Earned', 'Cash earned'] },
  { key: 'interestEarned', aliases: ['Interest Earned', 'Interest earned'] },
  { key: 'gemBlocksTapped', aliases: ['Gem Blocks Tapped'] },
  { key: 'damageTaken', aliases: ['Damage Taken'] },
  { key: 'damageTakenWall', aliases: ['Damage Taken Wall'] },
  { key: 'damageTakenWhileBerserked', aliases: ['Damage Taken While Berserked'] },
  { key: 'damageGainFromBerserk', aliases: ['Damage Gain From Berserk'] },
  { key: 'deathDefy', aliases: ['Death Defy'] },
  { key: 'damageDealt', aliases: ['Damage Dealt', 'Damage dealt'] },
  { key: 'projectilesDamage', aliases: ['Projectiles Damage'] },
  { key: 'rendArmorDamage', aliases: ['Rend Armor Damage'] },
  { key: 'projectilesCount', aliases: ['Projectiles Count'] },
  { key: 'lifesteal', aliases: ['Lifesteal'] },
  { key: 'thornDamage', aliases: ['Thorn Damage', 'Thorn damage'] },
  { key: 'orbDamage', aliases: ['Orb Damage'] },
  { key: 'enemiesHitByOrbs', aliases: ['Enemies Hit by Orbs'] },
  { key: 'landMineDamage', aliases: ['Land Mine Damage'] },
  { key: 'landMinesSpawned', aliases: ['Land Mines Spawned'] },
  { key: 'deathRayDamage', aliases: ['Death Ray Damage'] },
  { key: 'smartMissileDamage', aliases: ['Smart Missile Damage'] },
  { key: 'innerLandMineDamage', aliases: ['Inner Land Mine Damage'] },
  { key: 'chainLightningDamage', aliases: ['Chain Lightning Damage'] },
  { key: 'deathWaveDamage', aliases: ['Death Wave Damage'] },
  { key: 'taggedByDeathWave', aliases: ['Tagged by Deathwave'] },
  { key: 'swampDamage', aliases: ['Swamp Damage'] },
  { key: 'blackHoleDamage', aliases: ['Black Hole Damage'] },
  { key: 'totalEnemies', aliases: ['Total Enemies'] },
  { key: 'destroyedByOrbs', aliases: ['Destroyed By Orbs'] },
  { key: 'destroyedByThorns', aliases: ['Destroyed By Thorns', 'Destroyed by Thorns'] },
  { key: 'destroyedByDeathRay', aliases: ['Destroyed By Death Ray', 'Destroyed by Death Ray'] },
  { key: 'destroyedByLandMine', aliases: ['Destroyed By Land Mine', 'Destroyed by Land Mine'] },
  { key: 'destroyedInSpotlight', aliases: ['Destroyed in Spotlight'] },
  { key: 'destroyedInGoldenBot', aliases: ['Destroyed in Golden Bot'] },
  { key: 'guardianCoinsStolen', aliases: ['Guardian Coins Stolen', 'Guardian coins stolen'] },
  { key: 'coinsFetched', aliases: ['Coins Fetched'] },
  { key: 'gemsFetched', aliases: ['Gems Fetched', 'Gems'] },
  { key: 'medalsFetched', aliases: ['Medals Fetched', 'Medals'] },
  { key: 'rerollShardsFetched', aliases: ['Reroll Shards Fetched', 'Reroll Shards'] },
  { key: 'cannonShardsFetched', aliases: ['Cannon Shards Fetched', 'Cannon Shards'] },
  { key: 'armorShardsFetched', aliases: ['Armor Shards Fetched', 'Armor Shards'] },
  { key: 'generatorShardsFetched', aliases: ['Generator Shards Fetched', 'Generator Shards'] },
  { key: 'coreShardsFetched', aliases: ['Core Shards Fetched', 'Core Shards'] },
  { key: 'commonModulesFetched', aliases: ['Common Modules Fetched', 'Common Modules'] },
  { key: 'rareModulesFetched', aliases: ['Rare Modules Fetched', 'Rare Modules'] },
  { key: 'basic', aliases: ['Basic'] },
  { key: 'fast', aliases: ['Fast'] },
  { key: 'tank', aliases: ['Tank'] },
  { key: 'ranged', aliases: ['Ranged'] },
  { key: 'boss', aliases: ['Boss'] },
  { key: 'protector', aliases: ['Protector'] },
  { key: 'totalElites', aliases: ['Total Elites'] },
  { key: 'vampires', aliases: ['Vampires'] },
  { key: 'rays', aliases: ['Rays'] },
  { key: 'scatters', aliases: ['Scatters'] },
  { key: 'saboteurs', aliases: ['Saboteurs', 'Saboteur'] },
  { key: 'commanders', aliases: ['Commanders', 'Commander'] },
  { key: 'overcharges', aliases: ['Overcharges', 'Overcharge'] },
] as const

export const TRACK_RUN_SUBMIT_ALIAS_GROUPS: readonly RunDataAliasGroup[] = [
  { key: 'cashEarned', aliases: ['Cash Earned', 'Cash earned'] },
  { key: 'interestEarned', aliases: ['Interest Earned', 'Interest earned'] },
  { key: 'gemBlocksTapped', aliases: ['Gem Blocks Tapped'] },
  { key: 'damageTaken', aliases: ['Damage Taken'] },
  { key: 'damageTakenWall', aliases: ['Damage Taken Wall'] },
  { key: 'damageTakenWhileBerserked', aliases: ['Damage Taken While Berserked'] },
  { key: 'damageGainFromBerserk', aliases: ['Damage Gain From Berserk'] },
  { key: 'deathDefy', aliases: ['Death Defy'] },
  { key: 'damageDealt', aliases: ['Damage Dealt', 'Damage dealt'] },
  { key: 'projectilesDamage', aliases: ['Projectiles Damage'] },
  { key: 'rendArmorDamage', aliases: ['Rend Armor Damage'] },
  { key: 'projectilesCount', aliases: ['Projectiles Count'] },
  { key: 'lifesteal', aliases: ['Lifesteal'] },
  { key: 'thornDamage', aliases: ['Thorn Damage', 'Thorn damage'] },
  { key: 'orbDamage', aliases: ['Orb Damage'] },
  { key: 'enemiesHitByOrbs', aliases: ['Enemies Hit by Orbs', 'Destroyed By Orbs'] },
  { key: 'landMineDamage', aliases: ['Land Mine Damage'] },
  { key: 'landMinesSpawned', aliases: ['Land Mines Spawned'] },
  { key: 'deathRayDamage', aliases: ['Death Ray Damage'] },
  { key: 'smartMissileDamage', aliases: ['Smart Missile Damage'] },
  { key: 'innerLandMineDamage', aliases: ['Inner Land Mine Damage'] },
  { key: 'chainLightningDamage', aliases: ['Chain Lightning Damage'] },
  { key: 'deathWaveDamage', aliases: ['Death Wave Damage'] },
  { key: 'taggedByDeathWave', aliases: ['Tagged by Deathwave'] },
  { key: 'swampDamage', aliases: ['Swamp Damage'] },
  { key: 'blackHoleDamage', aliases: ['Black Hole Damage'] },
  { key: 'spotlightDamage', aliases: ['Spotlight Damage'] },
  { key: 'totalEnemies', aliases: ['Total Enemies'] },
  { key: 'destroyedInSpotlight', aliases: ['Destroyed in Spotlight'] },
  { key: 'destroyedInGoldenBot', aliases: ['Destroyed in Golden Bot'] },
  { key: 'guardianCoinsStolen', aliases: ['Guardian Coins Stolen', 'Guardian coins stolen'] },
  { key: 'coinsFetched', aliases: ['Coins Fetched'] },
  { key: 'gemsFetched', aliases: ['Gems Fetched', 'Gems'] },
  { key: 'medalsFetched', aliases: ['Medals Fetched', 'Medals'] },
  { key: 'rerollShardsFetched', aliases: ['Reroll Shards Fetched', 'Reroll Shards'] },
  { key: 'cannonShardsFetched', aliases: ['Cannon Shards Fetched', 'Cannon Shards'] },
  { key: 'armorShardsFetched', aliases: ['Armor Shards Fetched', 'Armor Shards'] },
  { key: 'generatorShardsFetched', aliases: ['Generator Shards Fetched', 'Generator Shards'] },
  { key: 'coreShardsFetched', aliases: ['Core Shards Fetched', 'Core Shards'] },
  { key: 'commonModulesFetched', aliases: ['Common Modules Fetched', 'Common Modules'] },
  { key: 'rareModulesFetched', aliases: ['Rare Modules Fetched', 'Rare Modules'] },
  { key: 'guardianSummonedEnemies', aliases: ['Summoned enemies', 'Summoned Enemies'] },
] as const

const TRACK_RUN_EXTRA_BATTLE_REPORT_LABELS = [
  'Battle Date',
  'Game Time',
  'Duration',
  'Coins per hour',
  'Deathwave Damage',
  'Tagged by Death Wave',
  'Electrons Damage',
  'Waves Skipped',
  'Recovery Packages',
  'Free Attack Upgrade',
  'Free Defense Upgrade',
  'Free Utility Upgrade',
  'Guardian Damage',
  'HP From Deathwave',
  'HP From Death Wave',
  'Coins From Deathwave',
  'Coins From Death Wave',
  'Cash From Golden Tower',
  'Coins From Golden Tower',
  'Coins From Black Hole',
  'Coins From Spotlight',
  'Coins From Orb',
  'Coins From Orbs',
  'Coins from Coin Upgrade',
  'Coins from Coin Bonuses',
  'Flame Bot Damage',
  'Thunder Bot Stuns',
  'Golden Bot Coins Earned',
  'Damage',
] as const

function uniqueLabels(values: readonly string[]): string[] {
  return Array.from(new Set(values.map(value => String(value).trim()).filter(Boolean)))
}

export const TRACK_RUN_INLINE_BATTLE_REPORT_LABELS: readonly string[] = uniqueLabels([
  ...TRACK_RUN_EXTRA_BATTLE_REPORT_LABELS,
  ...TRACK_RUN_OUTPUT_ALIAS_GROUPS.flatMap(group => group.aliases),
  ...TRACK_RUN_SUBMIT_ALIAS_GROUPS.flatMap(group => group.aliases),
])