export {
  TRACK_RUN_BATTLE_REPORT_SECTION_HEADERS,
  TRACK_RUN_CANONICAL_REPORT_LABEL_BY_KEY,
  TRACK_RUN_INLINE_BATTLE_REPORT_LABELS,
  TRACK_RUN_INLINE_BATTLE_REPORT_SECTION_LABELS,
  TRACK_RUN_OUTPUT_ALIAS_GROUPS,
  TRACK_RUN_SUBMIT_ALIAS_GROUPS,
} from '@tmrxjd/platform/tools'
export type { RunDataAliasGroup } from '@tmrxjd/platform/tools'