export const TRACKER_IDS = {
  review: {
    typePrefix: 'tracker_type:',
    addNotePrefix: 'tracker_addnote:',
    fullParsePrefix: 'tracker_fullparse:',
    acceptPrefix: 'tracker_accept:',
    cancelPrefix: 'tracker_cancel:',
    editPrefix: 'tracker_edit:',
    editFieldPrefix: 'tracker_edit_field:',
    editNotesPrefix: 'tracker_edit_notes:',
    editDonePrefix: 'tracker_edit_done:',
    noteModalPrefix: 'tracker_note_modal:',
    noteText: 'tracker_note_text',
    editModalPrefix: 'tracker_edit_modal:',
    editValue: 'tracker_edit_value',
  },
  manual: {
    typePrefix: 'tracker_manual_type:',
    notePrefix: 'tracker_manual_note:',
    nextPrefix: 'tracker_mnav_next:',
    editCorePrefix: 'tracker_mnav_edit1',
    editCoreTokenPrefix: 'tracker_medit1:',
    editExtraPrefix: 'tracker_medit2:',
    backPrefix: 'tracker_mnav_back',
    modalOnePrefix: 'tracker_manual_modal1:',
    modalTwoPrefix: 'tracker_manual_modal2:',
    modalPrefix: 'tracker_manual_modal:',
    noteModalPrefix: 'tracker_manual_note_modal:',
    noteText: 'tracker_manual_note_text',
  },
  flow: {
    uploadAnother: 'tracker_upload_another',
    mainMenu: 'tracker_main_menu',
    mainMenuAfterRemove: 'tracker_main_menu_after_remove',
    shareLast: 'tracker_share',
    upload: 'tracker_upload',
    paste: 'tracker_paste',
    addRun: 'tracker_addrun',
    addRunModal: 'tracker_addrun_modal',
    uploadModal: 'tracker_upload_modal',
    uploadRunType: 'upload_run_type',
    uploadNote: 'upload_note',
    uploadFile: 'upload_file',
    pasteModal: 'tracker_paste_modal',
    pasteText: 'tracker_paste_text',
    pasteNote: 'tracker_paste_note',
    addRunType: 'addrun_run_type',
    addRunPasteText: 'addrun_paste_text',
    addRunNote: 'addrun_note',
    addRunFile: 'addrun_file',
    manual: 'tracker_manual',
    editLast: 'tracker_editlast',
    shareLastMenu: 'tracker_sharelast',
    viewRuns: 'tracker_viewruns',
    support: 'tracker_support',
    removeLast: 'tracker_remove_last',
    cancel: 'tracker_cancel',
  },
  util: {
    cancelPlain: 'tracker_cancel_plain',
  },
  viewRuns: {
    columns: 'tracker_viewruns_columns',
    types: 'tracker_viewruns_types',
    tiers: 'tracker_viewruns_tiers',
    count: 'tracker_viewruns_select',
    orientation: 'tracker_viewruns_orientation',
    prev: 'tracker_viewruns_prev',
    next: 'tracker_viewruns_next',
    share: 'tracker_share_runs',
    shareSelectPrefix: 'tracker_share_runs_select:',
    shareConfirmPrefix: 'tracker_share_runs_confirm:',
    shareEditPrefix: 'tracker_share_runs_edit:',
    shareDeletePrefix: 'tracker_share_runs_delete:',
    shareCancelPrefix: 'tracker_share_runs_cancel:',
  },
  remove: {
    confirmPrefix: 'tracker_confirm_remove:',
    cancel: 'tracker_cancel_remove',
  },
  settings: {
    menu: 'tracker_settings',
    duplicates: 'tracker_setting_duplicates',
    confirm: 'tracker_setting_confirm',
    shareNotes: 'tracker_setting_share_notes',
    shareCoverage: 'tracker_setting_share_coverage',
    shareScreenshot: 'tracker_setting_share_screenshot',
    shareElements: 'tracker_setting_share_elements',
    shareBack: 'tracker_setting_share_back',
    language: 'tracker_language_select',
    timezone: 'tracker_timezone_select',
    tracker: 'tracker_tracker_select',
    defaultType: 'tracker_default_type_select',
    cloudToggle: 'tracker_cloud_toggle',
    forceSave: 'tracker_force_save_now',
    logChannel: 'tracker_setting_log_channel',
    logChannelModal: 'tracker_setting_log_channel_modal',
    logChannelValue: 'tracker_setting_log_channel_value',
    logChannelCategory: 'tracker_setting_log_channel_category',
    logChannelName: 'tracker_setting_log_channel_name',
    share: 'tracker_setting_share',
    stats: 'tracker_stats',
    import: 'tracker_import',
    importYes: 'tracker_import_yes',
    importNo: 'tracker_import_no',
  },
} as const;

export function withToken(prefix: string, token: string) {
  return `${prefix}${token}`;
}

export function withTokenAndField(prefix: string, token: string, field: string) {
  return `${prefix}${token}:${field}`;
}
