import { TrackerBotClient } from '../core/tracker-bot-client';
import {
  handleCancel,
  handleDataSubmission,
  handleEditDone,
  handleEditFieldSelection,
  handleEditNotesRequest,
  handleEditRequest,
  handleAddNote,
  handleShowFullParse,
  handleTypeSelection,
  handleTrackMenuAddRun,
  handleTrackMenuCancel,
  handleTrackMenuEditLast,
  handleTrackMenuManual,
  handleTrackMenuPaste,
  handleTrackMenuSupport,
  handleTrackMenuSettings,
  handleTrackMenuForceSave,
  handleTrackMenuSelectDefaultRunType,
  handleTrackMenuSelectLanguage,
  handleTrackMenuSetLogChannel,
  handleTrackMenuSelectTimezone,
  handleTrackMenuShareSettings,
  handleTrackMenuStats,
  handleTrackMenuToggleConfirm,
  handleTrackMenuToggleCloud,
  handleTrackMenuToggleDuplicates,
  handleTrackMenuShareElements,
  handleTrackMenuShareBack,
  handleTrackMenuUpload,
  handleTrackMenuUploadAnother,
  handleTrackMenuViewRuns,
  handleTrackMenuViewRunsColumns,
  handleTrackMenuViewRunsNext,
  handleTrackMenuViewRunsPrev,
  handleTrackMenuViewRunsSelect,
  handleTrackMenuViewRunsOrientation,
  handleTrackMenuViewRunsTiers,
  handleTrackMenuViewRunsTypes,
  handleTrackMenuImport,
  handleTrackMenuImportNo,
  handleTrackMenuImportYes,
  handleTrackMenuCancelRemove,
  handleTrackMenuConfirmRemove,
  handleTrackMenuRemoveLastPrompt,
  handleTrackMenuShareRuns,
  handleTrackMenuShareRunsCancel,
  handleTrackMenuShareRunsConfirm,
  handleTrackMenuShareRunsDelete,
  handleTrackMenuShareRunsEdit,
  handleTrackMenuShareRunsSelect,
  handleManualBackToMenu,
  handleManualEditStageOne,
  handleManualEditStageTwo,
  handleManualNext,
  handleManualNote,
  handleManualTypeSelection,
  handleTrackMenuShareLast,
  handleTrackMenuMainMenu,
} from '../features/track/handlers';
import { TRACKER_IDS } from '../features/track/track-custom-ids';

export function registerComponentHandlers(client: TrackerBotClient) {
  client.components.registerMany([
    { prefix: TRACKER_IDS.review.typePrefix, handler: handleTypeSelection },
    { prefix: TRACKER_IDS.review.addNotePrefix, handler: handleAddNote },
    { prefix: TRACKER_IDS.review.fullParsePrefix, handler: handleShowFullParse },
    { prefix: TRACKER_IDS.review.acceptPrefix, handler: handleDataSubmission },
    { prefix: TRACKER_IDS.flow.cancel, handler: handleCancel },
    { prefix: TRACKER_IDS.review.editPrefix, handler: handleEditRequest },
    { prefix: TRACKER_IDS.review.editFieldPrefix, handler: handleEditFieldSelection },
    { prefix: TRACKER_IDS.review.editNotesPrefix, handler: handleEditNotesRequest },
    { prefix: TRACKER_IDS.review.editDonePrefix, handler: handleEditDone },
    // Manual flow specific (registered before base manual button to avoid prefix collisions)
    { prefix: TRACKER_IDS.manual.typePrefix, handler: handleManualTypeSelection },
    { prefix: TRACKER_IDS.manual.notePrefix, handler: handleManualNote },
    { prefix: TRACKER_IDS.manual.nextPrefix, handler: handleManualNext },
    { prefix: TRACKER_IDS.manual.editCorePrefix, handler: handleManualEditStageOne },
    { prefix: TRACKER_IDS.manual.editCoreTokenPrefix, handler: handleManualEditStageOne },
    { prefix: TRACKER_IDS.manual.editExtraPrefix, handler: handleManualEditStageTwo },
    { prefix: TRACKER_IDS.manual.backPrefix, handler: handleManualBackToMenu },
    { prefix: TRACKER_IDS.flow.uploadAnother, handler: handleTrackMenuUploadAnother },
    { prefix: TRACKER_IDS.flow.mainMenu, handler: handleTrackMenuMainMenu },
    { prefix: TRACKER_IDS.flow.shareLast, handler: handleTrackMenuShareLast },
    { prefix: TRACKER_IDS.flow.upload, handler: handleTrackMenuUpload },
    { prefix: TRACKER_IDS.flow.paste, handler: handleTrackMenuPaste },
    { prefix: TRACKER_IDS.flow.addRun, handler: handleTrackMenuAddRun },
    { prefix: TRACKER_IDS.flow.manual, handler: handleTrackMenuManual },
    { prefix: TRACKER_IDS.flow.editLast, handler: handleTrackMenuEditLast },
    { prefix: TRACKER_IDS.flow.shareLastMenu, handler: handleTrackMenuShareLast },
    { prefix: TRACKER_IDS.flow.viewRuns, handler: handleTrackMenuViewRuns },
    { prefix: TRACKER_IDS.flow.support, handler: handleTrackMenuSupport },
    { prefix: TRACKER_IDS.settings.menu, handler: handleTrackMenuSettings },
    { prefix: TRACKER_IDS.settings.forceSave, handler: handleTrackMenuForceSave },
    { prefix: TRACKER_IDS.settings.duplicates, handler: handleTrackMenuToggleDuplicates },
    { prefix: TRACKER_IDS.settings.confirm, handler: handleTrackMenuToggleConfirm },
    { prefix: TRACKER_IDS.settings.shareElements, handler: handleTrackMenuShareElements },
    { prefix: TRACKER_IDS.settings.shareBack, handler: handleTrackMenuShareBack },
    { prefix: TRACKER_IDS.settings.language, handler: handleTrackMenuSelectLanguage },
    { prefix: TRACKER_IDS.settings.logChannel, handler: handleTrackMenuSetLogChannel },
    { prefix: TRACKER_IDS.settings.timezone, handler: handleTrackMenuSelectTimezone },
    { prefix: TRACKER_IDS.settings.defaultType, handler: handleTrackMenuSelectDefaultRunType },
    { prefix: TRACKER_IDS.viewRuns.columns, handler: handleTrackMenuViewRunsColumns },
    { prefix: TRACKER_IDS.viewRuns.types, handler: handleTrackMenuViewRunsTypes },
    { prefix: TRACKER_IDS.viewRuns.tiers, handler: handleTrackMenuViewRunsTiers },
    { prefix: TRACKER_IDS.viewRuns.count, handler: handleTrackMenuViewRunsSelect },
    { prefix: TRACKER_IDS.viewRuns.orientation, handler: handleTrackMenuViewRunsOrientation },
    { prefix: TRACKER_IDS.viewRuns.prev, handler: handleTrackMenuViewRunsPrev },
    { prefix: TRACKER_IDS.viewRuns.next, handler: handleTrackMenuViewRunsNext },
    { prefix: TRACKER_IDS.viewRuns.share, handler: handleTrackMenuShareRuns },
    { prefix: TRACKER_IDS.viewRuns.shareSelectPrefix, handler: handleTrackMenuShareRunsSelect },
    { prefix: TRACKER_IDS.viewRuns.shareConfirmPrefix, handler: handleTrackMenuShareRunsConfirm },
    { prefix: TRACKER_IDS.viewRuns.shareEditPrefix, handler: handleTrackMenuShareRunsEdit },
    { prefix: TRACKER_IDS.viewRuns.shareDeletePrefix, handler: handleTrackMenuShareRunsDelete },
    { prefix: TRACKER_IDS.viewRuns.shareCancelPrefix, handler: handleTrackMenuShareRunsCancel },
    { prefix: TRACKER_IDS.remove.confirmPrefix, handler: handleTrackMenuConfirmRemove },
    { prefix: TRACKER_IDS.remove.cancel, handler: handleTrackMenuCancelRemove },
    { prefix: TRACKER_IDS.flow.mainMenuAfterRemove, handler: handleTrackMenuCancelRemove },
    { prefix: TRACKER_IDS.flow.removeLast, handler: handleTrackMenuRemoveLastPrompt },
    { prefix: TRACKER_IDS.settings.cloudToggle, handler: handleTrackMenuToggleCloud },
    { prefix: TRACKER_IDS.settings.share, handler: handleTrackMenuShareSettings },
    { prefix: TRACKER_IDS.settings.stats, handler: handleTrackMenuStats },
    { prefix: TRACKER_IDS.settings.importYes, handler: handleTrackMenuImportYes },
    { prefix: TRACKER_IDS.settings.importNo, handler: handleTrackMenuImportNo },
    { prefix: TRACKER_IDS.settings.import, handler: handleTrackMenuImport },
    { prefix: TRACKER_IDS.flow.cancel, handler: handleTrackMenuCancel },
  ]);
}
